version: "3"

services:
  nodeosd:
    hostname: nodeosd
    image: eosio/eos:v1.3.0
    entrypoint: nodeos
    command: >
      --data-dir /opt/eosio/bin/data-dir
      --enable-stale-production
      --http-server-address=0.0.0.0:8888
      --http-alias=nodeosd:8888
      --http-alias=127.0.0.1:8888
      --http-alias=localhost:8888
      --https-server-address=0.0.0.0:8889
      --http-alias=nodeosd:8889
      --http-alias=127.0.0.1:8889
      --http-alias=localhost:8889
      --https-certificate-chain-file=/docker/cert.pem
      --https-private-key-file=/docker/key.pem
      --access-control-allow-origin=*
      --contracts-console
      --plugin eosio::chain_api_plugin
      --plugin eosio::history_api_plugin
      --chain-state-db-size-mb=8192
      --reversible-blocks-db-size-mb=340
      --producer-name=eosio
    volumes:
      - nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./docker:/docker:ro
    ports:
      - 8888:8888
      - 8889:8889
      - 9876:9876
    expose:
      - "8888"
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    hostname: keosd
    image: eosio/eos:v1.3.0
    entrypoint: keosd
    command: >
      --wallet-dir /opt/eosio/bin/data-dir
      --http-server-address=127.0.0.1:8900
      --http-alias=keosd:8900
      --http-alias=localhost:8900
      --unlock-timeout=99999999
    ports:
      - 8900:8900
    volumes:
      - keosd-data-volume:/opt/eosio/bin/data-dir
      - ./target/wasm32-unknown-unknown/release:/mnt/dev/release:ro
      - ./contract:/mnt/dev/contract:ro
    links:
      - nodeosd
    stop_grace_period: 10m

volumes:
  nodeos-data-volume:
    external: true
  keosd-data-volume:
    external: true
